### ISSUE TITLE
CSI amplitude & phase

### ISSUE THREAD

**Issue by tiyuuu** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#10]
From CSI dataset we can see amplitude and phase for each frame. By those amplitude and phase frame what we can understand??

**Comment by jonathanmuller** [comment]
Hi, 

The question is very broad and I believe there are no exhaustive list, but here are few examples :
- Amplitude is more accurate than the RSSI (because it's "sampled" over more data), so it can be used to determine the distance from the AP
- Phase (change) can be used to determine the speed of the device (typically in NLOS scenario)
